version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY}webapp
    build:
      context: .
      dockerfile: src/webapps/WebApp/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY}identityapi
    build:
      context: .
      dockerfile: src/services/Identity.API/Dockerfile


  chat.api:
    image: ${DOCKER_REGISTRY}chatapi
    build:
      context: .
      dockerfile: src/services/Chat.API/Dockerfile

